backend = "glx";
vsync = true;

shadow = true;
shadow-radius = 10;
shadow-offset-x = -10;
shadow-offset-y = -10;
shadow-opacity = 0.7;

fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;

use-damage = false;
detect-client-opacity = false;

opacity-rule = [
  "75:class_g = 'Alacritty'",
  "75:class_g = 'St'",
  "70:class_g = 'URxvt'",
  "95:class_g = 'firefox-default'",
  "55:class_g = 'konsole'",
  "60:class_g = '*'"
];

